# Copyright: Krzysztof Kowalczyk
# Owner: Krzysztof Kowalczyk
#
# Purpose:
#   Import data from *.csv file with reg codes generated by inoah_gen_reg_codes.py
#   into a database so that the server can properly authenticate users.

import sys,os,csv
import inoah_gen_reg_codes

def main():
    codes = inoah_gen_reg_codes.readPreviousCodes()
    for c in codes.keys():
        print c

if __name__=="__main__":
    main()

