# Generated by multilink -gdb-script option
define load-segments
  set $jmptable = *((long**)($a5-4))
  echo loading segments
  echo .
  add-symbol-file a0001.out *(long*)(((long)$jmptable)+4)
  echo .
  add-symbol-file a0002.out *(long*)(((long)$jmptable)+8)
  echo done\n
end
document load-segments
  load-segments command for a.out (3 segments)
  Use the load-segments command to load the non-zeroth segments
  in a multi-segment application. This allows you do debug code
  in any segment.
end
