
#define formDictMain 1000

#define	menuMain	1100
#define	menuEditCopy	 1200
#define	menuEditPaste	1201
#define	menuEditPreferences	1202

#define alertMemError                               2000
#define alertRomIncompatible                    2001
#define alertNetworkLibraryNotFound          2002
#define alertUnableToInitializeNetLibrary     2003
#define alertWordNotFound                        2004
#define alertMalformedResponse                2005
#define alertCustomError	                     2006

#define bmpFind             3000

#define	scrollDef	4000
#define	buttonFind	4001
#define   fieldWordInput 4002
#define	labelWord	4003
//
// Autogenerated symbols - 2003-12-31 14:43:52
// Falch.net PilRC Designer
//
// Autogenerated symbols - 2004-01-01 14:43:48
// Falch.net PilRC Designer
//
//
