#define _ADD_FIND_WORD_PATTERN_ 1

#define   formDictMain        1008
#define   formDictFind        1002
#define   formDictFindPattern 1003
#define   formSelectDict      1004
#define   formPrefs           1005
#define   formDisplayPrefs    1006
#define	formResidentLookup	1007

#define   fieldWord           1200

#define   ctlArrowLeft        1300
#define   ctlArrowRight       1301

#define   listMatching        1400
#define   listOfDicts         1401
#define   listHistory         1402
#define   listStartupAction   1403
#define   listStartupDB       1404
#define   listhwButtonsAction 1405
#define   listTapAction       1406

#define   alertMemError       1100
#define   alertNoDB           1109
#define   alertDBName         1112
#define   alertBadRecSize     1113
#define   alertGenericError   1114
#define   alertDbFailed       1115
#define   alertDbFailedGetAnother 1116
#define	alertWordNotFound	1117

#define   menuMain            2000
#define   menuItemSelectDB    2002
#define   menuItemFind        2004
#define   menuItemFindPattern 2005
#define   menuItemHelp        2006
#define   menuItemStress      2008
#define   menuItemAbout       2010
#define   menuItemPrefs       2012
#define   menuItemCopy        2014
#define   menuItemTranslate   2016
#define   menuItemDispPrefs   2018

#define   buttonCancel        3001
#define   buttonFind          3002
#define   buttonSelect        3003
#define   buttonOk            3004
#define   buttonHeadword      3005
#define   buttonDefinition    3006
#define   buttonExample       3007
#define   buttonRescanDicts   3008
#define   buttonOneChar       3009
#define   buttonAnyChar       3010
#define	buttonClose	3011

#define   scrollDef           4008

#define   bmpFind             5001
#define   bmpLogo             5011

#define   popupHistory            6001
#define   popupStartupAction      6002
#define   popupStartupDB          6003
#define   popuphwButtonsAction    6004
#define   popupTapAction          6005

// #define   checkDeleteVfs          6500

//
// Autogenerated symbols - 2003-12-09 15:00:38
// Falch.net PilRC Designer
//
#define   helpPrefs               7001
